### ISSUE TITLE
Add the possibility to load "template" projects or systems

### ISSUE THREAD

**Issue by maxboone** [ai4mde/studio#25]
**Summary**

We want users to be able to boot up the studio, and load up a project or system template with prefilled diagrams and application model details. This as a bootstrap or starting point to model the application in the toolkit.

**Possible implementation**

- Create a folder in the Django-application which will hold static files with configuration
- Create JSON (or YAML) files that contain fixtures for these templates
- Create an endpoint that takes a name and whether it needs to add the template to an existing project or create a new one
- The endpoint loads the template file and enumerates over the objects creating them in the right context

An example (YAML) for this fixture would be:

```yaml
- name: Fulfilment System
  type: system
  id: 1
  classifiers:
    - id: 1
      name: Customer
      attributes:
        - name
        - age
    - id: 2
      name: Order
      attributes:
  relationships:
    - id: 1
      type: Association
      from: 1
      to: 1
      multiplicity:
        from: 1
        to: "*"
```

Model this as close to the metamodel (JSONSchema / Pydantic) as possible. Note that we just use integers for identification here, the endpoint should track the generated / created UUIDs for these objects and use those to create the relations. These IDs are only local to the fixture and should by no means end up in the database literally.
